[package]
name = "rust-geodesic-raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
image = { version = "=0.24.9", default-features = false, features = ["png", "rayon"] }
rayon = "1"


[profile.release]
codegen-units = 1
lto = true
